project_name: museek
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: museek
    binary: museek
    gcflags:
      - all=-l -B
    ldflags:
      - -s -w
      - -X github.com/ivaquero/museek/cmd.gitVersion={{ .Version }}
      - -X github.com/ivaquero/museek/cmd.gitCommit={{ .Commit }}
      - -X github.com/ivaquero/museek/cmd.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - loong64
    ignore:
      - goos: windows
        goarch: loong64
      - goos: darwin
        goarch: loong64

scoops:
  - repository:
      owner: scoopforge
      name: main-plus
      branch: main
    commit_author:
      name: ivaquero
      email: msaintms@outlook.com
    homepage: 'https://github.com/ivaquero'
    description: 'Command-line to download music from Internet.'
    license: BSD 2-Clause

brews:
  - name: museek
    repository:
      owner: brewforge
      name: homebrew-more
      branch: main
    commit_author:
      name: ivaquero
      email: msaintms@outlook.com
    directory: Formula
    homepage: 'https://github.com/ivaquero'
    description: 'Command-line to download music from Internet.'
    license: 'BSD 2-Clause'
    install: |
      bin.install "museek"

      # Install shell completions
      output = Utils.safe_popen_read("#{bin}/museek", "completion", "bash")
      (bash_completion/"museek").write output

      output = Utils.safe_popen_read("#{bin}/museek", "completion", "zsh")
      (zsh_completion/"_museek").write output

      output = Utils.safe_popen_read("#{bin}/museek", "completion", "fish")
      (fish_completion/"museek.fish").write output
    test: |
      system "#{bin}/museek version"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^web:'
      - '^build:'

archives:
  - id: museek
    builds:
      - museek
    format: tar.gz
    wrap_in_directory: 'true'
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

snapshot:
  version_template: '{{ incminor .Version }}-next'
